import 'dart:convert';
import 'package:http/http.dart' as http;

import 'model_class.dart';

class ApiService {
  final String apiUrl = 'https://grozziie.zjweiting.com:8033/tht/allIcons';

  Future<List<Autogenerated>> fetchIcons() async {
    try {
      final response = await http.get(Uri.parse(apiUrl));

      if (response.statusCode == 200) {
        final jsonData = json.decode(response.body);
        List<Autogenerated> icons = [];
        for (var item in jsonData) {
          icons.add(Autogenerated.fromJson(item));
        }
        return icons;
      } else {
        throw Exception('Failed to load icons');
      }
    } catch (e) {
      throw Exception('Check your internet connection');
    }
  }

}
